import type { Metadata } from "next";
import "./globals.css";
// import { Toaster } from "react-hot-toast";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Clever Path Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <Toaster
          position="top-center"
          gutter={8}
          toastOptions={{ duration: 2500 }}
        />
      </body>
    </html>
  );
}
